# Generated by Django 4.2.5 on 2023-10-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('price', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ShopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('lng', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sinnoh_stores.inventory')),
                ('products', models.ManyToManyField(to='sinnoh_stores.productlister')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('quantity', models.PositiveIntegerField(default=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinnoh_stores.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('hashed_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('orderer', models.CharField(default='', max_length=128)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinnoh_stores.shoplocation')),
                ('products', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sinnoh_stores.inventory')),
            ],
        ),
    ]
