# Generated by Django 4.2.5 on 2023-11-03 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinnoh_stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=64)),
                ('products', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sinnoh_stores.inventory')),
            ],
        ),
    ]
